#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : janus
Version  : 0.6.2
Release  : 7
URL      : https://files.pythonhosted.org/packages/fc/8e/92fcb2ff18797959cde050b7c96a713999f73feefde809bfdf18b5901174/janus-0.6.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/fc/8e/92fcb2ff18797959cde050b7c96a713999f73feefde809bfdf18b5901174/janus-0.6.2.tar.gz
Summary  : Mixed sync-async queue to interoperate between asyncio tasks and classic threads
Group    : Development/Tools
License  : Apache-2.0
Requires: janus-license = %{version}-%{release}
Requires: janus-python = %{version}-%{release}
Requires: janus-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pip
BuildRequires : pytest-asyncio-python

%description
=======
janus
=======
.. image:: https://travis-ci.com/aio-libs/janus.svg?branch=master
:target: https://travis-ci.com/aio-libs/janus
.. image:: https://codecov.io/gh/aio-libs/janus/branch/master/graph/badge.svg
:target: https://codecov.io/gh/aio-libs/janus
.. image:: https://img.shields.io/pypi/v/janus.svg
:target: https://pypi.python.org/pypi/janus
.. image:: https://badges.gitter.im/Join%20Chat.svg
:target: https://gitter.im/aio-libs/Lobby
:alt: Chat on Gitter

%package license
Summary: license components for the janus package.
Group: Default

%description license
license components for the janus package.


%package python
Summary: python components for the janus package.
Group: Default
Requires: janus-python3 = %{version}-%{release}

%description python
python components for the janus package.


%package python3
Summary: python3 components for the janus package.
Group: Default
Requires: python3-core
Provides: pypi(janus)

%description python3
python3 components for the janus package.


%prep
%setup -q -n janus-0.6.2
cd %{_builddir}/janus-0.6.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1635115992
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}$(python -c "import sys; print(sys.path[-1])") python setup.py test
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/janus
cp %{_builddir}/janus-0.6.2/LICENSE %{buildroot}/usr/share/package-licenses/janus/840d2e227459bbd5c33423550411f4dac2758ee5
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/janus/840d2e227459bbd5c33423550411f4dac2758ee5

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
