#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : janus
Version  : 0.6.1
Release  : 3
URL      : https://files.pythonhosted.org/packages/7c/1b/8769c2dca84dd8ca92e48b14750c7106ff4313df4fee651dbc3cd9e345a9/janus-0.6.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/7c/1b/8769c2dca84dd8ca92e48b14750c7106ff4313df4fee651dbc3cd9e345a9/janus-0.6.1.tar.gz
Summary  : Mixed sync-async queue to interoperate between asyncio tasks and classic threads
Group    : Development/Tools
License  : Apache-2.0
Requires: janus-python = %{version}-%{release}
Requires: janus-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pytest-asyncio-python

%description
janus
        =======

%package python
Summary: python components for the janus package.
Group: Default
Requires: janus-python3 = %{version}-%{release}

%description python
python components for the janus package.


%package python3
Summary: python3 components for the janus package.
Group: Default
Requires: python3-core
Provides: pypi(janus)

%description python3
python3 components for the janus package.


%prep
%setup -q -n janus-0.6.1
cd %{_builddir}/janus-0.6.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1608052368
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}$(python -c "import sys; print(sys.path[-1])") python setup.py test
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
